### ISSUE TITLE
Native Item export path missing file extention

### ISSUE THREAD

**Issue by marleyjaffe** [Nuix/Custom-Exporter#12]
Hello, we are finding that in some scenarios, the ItemPath field is missing the file extension. This is not an issue when we perform an export using the workstation built in UI for legal export. It seems like the missing extensions are related to Teams Message items or calendar items. 
Custom Export Script:
![CustomExportScript](https://github.com/Nuix/Custom-Exporter/assets/3719336/b0ea028b-2dba-4f5a-832b-ea406257c718)

Manual Export from UI:
![ManualExportUI](https://github.com/Nuix/Custom-Exporter/assets/3719336/0f81a329-15c8-48a2-a82c-c46e466d13ac)

**Comment by JuicyDragon** [comment]
I suspect it has to do with this code used by the script to determine what extension to apply when restructuring the exported data (which also updates the appropriate columns in the DAT).

https://github.com/Nuix/Custom-Exporter/blob/781a281b79e32076f095f1ddc63c8342c1cdb9ab/Ruby/CustomExporter.nuixscript/CustomExporter.rb#L924-L937

I'm thinking what may be happening is that all of those API calls to get extension are returning empty string for those data types.  I'm thinking perhaps the logic could be improved by first looking to the exported native for what extension it has, falling back to this other logic if that fails for some reason.

**Comment by JuicyDragon** [comment]
I think I have a fix to address the issue, please try this release: https://github.com/Nuix/Custom-Exporter/releases/tag/v1.22.0

**Comment by marleyjaffe** [comment]
The new release seems to have solved the issue. Thank you for your quick turn around @JuicyDragon!

**Comment by JuicyDragon** [comment]
Excellent, glad to hear it! 😄
